# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 10:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('description', models.TextField(default='Good teacher')),
                ('registration_date', models.DateField(default=datetime.date(2017, 9, 19))),
                ('graduation_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
