# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 10:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akirachix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_date',
            field=models.DateField(default=datetime.date(2017, 9, 26)),
        ),
    ]
